#!/bin/bash

# run this script for installing driver for Archer T2U Plus -> 
sudo apt-get update
sudo apt-get upgrade
sudo apt install realtek-rtl88xxau-dkms
sudo apt install aircrack-ng 
# iwconfig -> for checking the driver 

# sudo airmon-ng check kill -> for kill the process that can create problem with the operation

# sudo aireplay-ng --test wlan0
# sudo airodump-ng --band a wlan0  -> for 5ghz networks 
# sudo airodump-ng --band bg wlan0 -> for 2.5ghz networks

